In [19]:
import numpy as np
        # [0.3014848 , -0.09280358,  0.94894384],
        # [0.3014848 , -0.09280358,  0.94894384],
        # [0.3014848 , -0.09280358,  0.94894384],
        # [0.3014848 , -0.09280358,  0.94894384],
        # [0.3014848 , -0.09280358,  0.94894384],
rays = np.stack((
        [-0.18745319,  0.93921852, -0.287628  ],
        [-0.06322262,  0.60274195, -0.79542759],
        [-0.37385775, -0.31259124, -0.87322225],
))

rays

# (rays[0,:] * rays[0+1:,:]).sum(-1) # gets the next row of the rays collection  


array([[-0.18745319,  0.93921852, -0.287628  ],
       [-0.06322262,  0.60274195, -0.79542759],
       [-0.37385775, -0.31259124, -0.87322225]])

In [20]:
rays[0+1:,:]


array([[-0.06322262,  0.60274195, -0.79542759],
       [-0.37385775, -0.31259124, -0.87322225]])

In [30]:
rays[0,:] * rays[0+1:,:]


array([[ 0.01185128,  0.5661064 ,  0.22878725],
       [ 0.07008083, -0.29359148,  0.25116317]])

In [33]:
(rays[0,:] * rays[0+1:,:]).sum(-1)


array([0.08193211, 0.27251492, 0.47995042])

In [47]:
d = np.arccos((rays[0,:] * rays[0+1:,:]).sum(-2))
np.flatnonzero(d < 4)


array([0, 1, 2])